# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/hugo
image: jojomi/hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  

pages:
  script:
  - rm -rf public
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
  
test:
  script:
  - rm -rf public
  - hugo
  except:
  - master
