MetaDataFormat: "yaml"
baseURL: "https://www.beyondpoliticsbook.com/"
# baseURL: "https://jonathan.pages.jgilligan.org/beyondpoliticsbook/"
title: "Beyond Politics"
copyright: "&copy; 2017 Jonathan Gilligan"
theme: "hugo-finisterre"
contentdir: "content"
layoutdir: "layouts"
datadir: "data"
staticdir: "static"
themesdir: "themes"
publishdir: "public"
builddrafts: false
pygmentsuseclasses: true
pygmentsStyle: "zenburn"
indexes:
  category: "categories"
  tag: "tags"
taxonomies:
  - category: "categories"
  - tag:      "tags"
canonifyUrls: true
relativeUrls: true
enableRobotsTXT: true
ignoreFiles: [ "~$", "^\\.", "\\.#", "\\.Rmd$", "_files$", "_cache$", "Corel Auto-Preserve$"]

menu:
  main:
      - Name: "In The News"
        Weight: 1
        Identifier: "news_parent"
      - Name: "In The News"
        Identifier: "news"
        URL: "/news/"
        Weight: 2
        Parent: "news_parent"
      - Name: "Reviews"
        URL: "/review/"
        Weight: 3
        Parent: "news_parent"
      - Name: "Endorse&shy;ments"
        URL: "/blurb/"
        weight: 4
      - Name: "Blog"
        Identifier: "blog_parent"
        Weight: 5
      - Name: "Podcasts"
        URL: "/podcast/"
        weight: 6
        Parent: "blog_parent"
      - Name: "Blog"
        URL: "/post/"
        Weight: 7
        Parent: "blog_parent"
      - Name: "Out&shy;line"
        URL: "/chapter/"
        Weight: 8
      - Name: "Actions"
        URL: "/actions/"
        Weight: 9
      - Name: "Further Reading"
        URL: "/reading/"
        Weight: 10
      - Name: "About the Au&shy;thors"
        URL: "/author/"
        Weight: 11
permalinks:
  post: /post/:year/:month/:day/:slug
  news: /news/:year/:month/:day/:slug
blackfriday:
  smartypants: true
  angledQuotes: false
  fractions: false
  smartDashes: true
  latexDashes: true
  hrefTargetBlank: true
# googleAnalytics: "UA-101117636-2"
params:
  web_designer_name: "Jonathan Gilligan"
  web_design_year: 2017
  typekitCode: "ktg3ojr"
  fontawesomeCode: "0cecfe2e0e"
  mathjax: false
  mhchem: false
  recent_count: 2
  recent_item_sections:
    - "news"
    - "post"
    - "review"
    - "podcast"
  front_page_img: "book_cover.jpg"
  book_avatar: "book_avatar.jpg"
  book_twitter: "beyondgridlock"
  book:
    title: "Beyond Politics: The Private Governance Response to Climate Change"
    short_title: "Beyond Politics"
    publisher: "Cambridge University Press"
    year: "2017"
    isbn: "9781316632482"
    social:
      twitter:
        priority: 4
        icon: "twitter"
        icon_pack: "fa"
        link: "https://twitter.com/beyondgridlock"
        text: "@beyondgridlock"
        on_site: "Twitter"
      indiebound:
        priority: 1
        icon: "info"
        icon_pack: "fa"
        text: "IndieBound"
        link: "http://www.indiebound.org/book/9781316632482"
      amazon:
        priority: 2
        icon: "amazon"
        icon_pack: "fa"
        text: "Amazon"
        link: "https://www.amazon.com/dp/1316632482"
      cup:
        priority: 3
        icon: "book"
        icon_pack: "fa"
        link: "http://www.cambridge.org/us/academic/subjects/politics-international-relations/political-economy/beyond-politics-private-governance-response-climate-change?format=PB#fIFIqQswJ56fKCq0.97"
        text: "Cambridge University Press"
  authors:
    jonathan:
      name: "Jonathan Gilligan"
      twitter: "jg_environ"
      cv_file: "gilligan_cv.pdf"
      organization: "Vanderbilt University"
      email: "jonathan.gilligan@vanderbilt.edu"
      front_page_img: "jg/jg_kokilmoni_deck_2010_large.jpg"
      avatar: "avatar.jpg"
      address:
        - "<a href=\"https://www.vanderbilt.edu/ees\">Department of Earth &amp; Environmental Sciences</a>,"
        - "<a href=\"https://www.vanderbilt.edu/\">Vanderbilt University</a><br/>"
        - "2301 Vanderbilt PL,"
        - "PMB 351805,<br/>"
        - "Nashville,"
        - "TN"
        - "37235-1805"
      social:
        phone:
          priority: 1
          icon: "phone"
          icon_pack: "fa"
          text: "615.322.2420"
        email:
          priority: 2
          icon: "envelope"
          icon_pack: "fa"
          link: "mailto:jonathan.gilligan@vanderbilt.edu"
          text: "jonathan.gilligan@vanderbilt.edu"
        twitter:
          priority: 4
          icon: "twitter"
          icon_pack: "fa"
          link: "https://twitter.com/jg_environ"
          text: "@jg_environ"
          on_site: "Twitter"
        github:
          priority: 8
          icon: "github"
          icon_pack: "fa"
          link: "https://github.com/jonathan-g"
          text: "jonathan-g"
          on_site: "GitHub"
        orcid:
          priority: 6
          icon: "orcid"
          icon_pack: "ai"
          link: "https://orcid.org/0000-0003-1375-6686"
          text: "0000-0003-1375-6686"
          site: "ORCID:"
        ssrn:
          priority: 7
          link: "https://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id=954061"
          text: "954061"
          site: "SSRN ID:"
        google_scholar:
          priority: 5
          icon: "google-scholar"
          icon_pack: "ai"
          link: "https://scholar.google.com/citations?user=B8RVAU0AAAAJ"
          text: "Google Scholar"
        skype:
          priority: 3
          icon: "skype"
          icon_pack: "fa"
          text: "jonathan_gilligan"
          on_site: "Skype"
    mike:
      name: "Michael Vandenbergh"
      organization: "Vanderbilt University"
      email: "michael.vandenbergh@vanderbilt.edu"
      address:
        - "<a href=\"https://law.vanderbilt.edu/\">Vandeerbilt Law School</a>,"
        - "<a href=\"https://www.vanderbilt.edu/\">Vanderbilt University</a><br/>"
        - "131 21st Ave. S.,<br/>"
        - "Nashville,"
        - "TN"
        - "37203-1181"
      social:
        phone:
          priority: 1
          icon: "phone"
          icon_pack: "fa"
          text: "615.322.6763"
        email:
          priority: 2
          icon: "envelope"
          icon_pack: "fa"
          link: "mailto:michael.vandenbergh@vanderbilt.edu"
          text: "michael.vandenbergh@vanderbilt.edu"
        ssrn:
          priority: 7
          link: "https://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id=426704"
          text: "426704"
          site: "SSRN ID:"
